id: P004405
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:18:46.055651
source_metadata:
  id: bdr:W1CZ1297
  title: དབང་གོང་མའི་ཆོ་ག་
  author: ''
  volumes:
    f787d373c04c47ec846f7da3f98e5ce3:
      image_group_id: I1CZ1815
      title: ''
      volume_number: 1
      total_pages: 32
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
