id: I2535D547
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T17:37:18+00:00'
last_modified: '2022-06-07T22:38:35.414460+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1297
  title: དབང་གོང་མའི་ཆོ་ག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    28CD:
      image_group_id: I1CZ1815
      title: ''
      total_pages: 32
      order: 1
      base_file: 28CD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
